// <auto-generated />
namespace FPT_Training_4._0.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class ClassCourseFix : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ClassCourseFix));
        
        string IMigrationMetadata.Id
        {
            get { return "202201030843054_ClassCourseFix"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
